server:
  port: 8761
spring:
  application:
    name: discovery
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      default-zone: http://localhost:8761/eureka