server:
  port: 9901
spring:
  application:
    name: multipay
  datasource:
    #        driver-class-name: oracle.jdbc.OracleDriver
    #        url: jdbc:oracle:thin:@192.168.0.34:1521:oradev
    #        username: sepahneopay
    #        password: sepahneopay
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:sepah.enopay
    username: sa
    password:
  jpa:
    show-sql: false
    #    database-platform: org.hibernate.dialect.OracleDialect
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 50MB
      file-size-threshold: 50MB
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  main:
    allow-bean-definition-overriding: true
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: payment
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
dotin:
  baseUrl: https://ib.ebanksepah.ir
  endpoints:
    restBatchDepositTransfer: /Api/IssueDocument
    restReverseTransfer: /Api/Reverse
    getAccountInfo: /Api/GetAccountInfo
    inquiryOtherBankIbanInfo: /StandardCore/InquiryOtherBankIbanInfo
    transferPaya: /TransferPublic/TransferPaya
    transferSatna: /TransferPublic/TransferSatna
    getStatementByAccountNumber: /Api/GetStatementByAccountNumber
    getCustomerDepositslist: /Api/GetCustomerDepositslist
    getEdghamStatus: /Edgham/Transaction/GetEdghamStatus
  apiKey: 7cbc24b0-eb29-472e-b4f5-c015f70af768
  privateKey: <RSAKeyValue><Modulus>8TEUzbR6glQy7YdJXxFDtZ4yCGMxvJyT626cV1+d6VpEcvIeemBucQ4EILxA52tySAXEK32dRFWKOLJo0r63NG+jPiMWhx8VEblQ+gryuiSZqwmdFeHvmrx7xNMBO6DUftc43Xg2rapPONEp/cboOjk0WaSc16CU2L6sJE2kff/PhGR8xCLjv6epybLUy6ZQz6EGHvumprBULM54MrrCrvY1ITYVo+9GZj4MYxcd5B/AfUfbSvB7IyutYfyP+aoYpXlsUcHpAa7Lne27Pd8GyKoqKv24AQ2kbtQPlLfzotyhVj50gHhqZ7sHFPxDVYdJVbNHXt9Z16hzLDlClJZpbQ==</Modulus><Exponent>AQAB</Exponent><P>8mmIAhQYOsjqLyQPZVnDHWoJywVte+4Aob4cJueplFyDuwjkapkD7t0BVO0UZU8rSL8+pF4F0UU3AMhdA4pbWgkU9fLKCklefQDQ2juaLqXlNV3Bpgl47PB5EcQ3fWcb/CKII7pFexv751ru57FE6SNpVhqGC8z3rUz+jm6HkQM=</P><Q>/rYJU65RnfJkq1e/f+fgdsXzE5JgDD88JlkGFG1oGHqL+Q44WuT+SLTh2j9ndXLOjI0feXYOQK98WJ3l/v+R6f7wSxUSpHyDCkSbThivkcfMbWGA/U4w6Fv2LZq3F2v+ice6yQxXLfqdwq8I6/W4ZoagZV3r2YuxvH3BRmjquM8=</Q><DP>cZeOChtMd09qnYhyRnXXflMQH7h9Y1NVrHUfUAPCbSkk+WHjVyg4tZeOZjNqGUcN61riibcdVsDuU0mQfHY69GfJEK8iictzoXPeakT/rNhEHcu/UISjy7Orp+2gav0EGhQ8YzGIGXY1hmYQCTYCKpVTaOuo4KK9dNHdfvTARe0=</DP><DQ>w9eHeFXx3zW+fZfsYBYTmn89FPFY9FGyl/GfIRm2Dgw7j3WFky267oBVn49cpwttENh5ONSyxL2pKCHP867hrD8e1zwOp3Ys8zopB3UnmTk8T2XG3fy+0gnTUOFCobmhbqKpVWgtp+aoYkZe376A2CPvM8FxVEV6lWlDsDV/NDU=</DQ><InverseQ>rXJL2mndSA2vulHwcvuemIStHjqaa5pCMg+aWTZ8p477q4lGI0vPoUZF9LePoBYuNj9b6P/Z26EnnQDj+CPv7nykUFA9WpqgC9HSArsDIy+qMI6ovfAtVt7hif/5/xBfMKQqDV86S/w39DoUTIRpskk+XfDX5nePWp+LdkNffG4=</InverseQ><D>sa9/7P+N1V/kWPr2wbO9VxphL66sIJCVpLdLNE87zYLztF7Mt0k9c8ponhkyE4sjmQ2udH/JEWOXPaep88AOxfGMqKU+3nK2meUVU/Am251FHC0r7cgSNcOvxtPQL7aPdZZmzTnXxl8Wl/v33H7h7Krh9zx/U5d4sKjftqsAiNUzNsIcFXfWNvCaYH6QpPLZNR7BBCSkzMKkK/9Eo+QCNJka7W6yjg4zg5whJi6B6bFXsCQysVM1pcd9z4/mM7BATnMbxQe7u/y/4hgrPCv9td0sHuCnGxdtrJ/qiAV+9L3CZ+3ZEsJji7pxikFNaZ86MQ3qA+sVDM4kggvsHZB0PQ==</D></RSAKeyValue>
  test:
    orgCode: 1002